apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: leafnoise-challenge
  labels:
    app: angular
spec:
  type: NodePort
  selector:
    app: angular
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
