services:
  web:
    image: ghcr.io/alfremu/flask-example:latest
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
