name: Build & Push (Backend + Frontend)

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/build-push.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/build-push.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  backend:
    name: Build & Push Backend (Flask)
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.changed_files, 'backend')
    steps:
      - uses: actions/checkout@v4

      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build y push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/alfremu/devops-challenge-flask-angular-backend:${{ github.sha }}
            ghcr.io/alfremu/devops-challenge-flask-angular-backend:latest

  frontend:
    name: Build & Push Frontend (Angular)
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.changed_files, 'frontend')
    steps:
      - uses: actions/checkout@v4

      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build y push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/alfremu/devops-challenge-flask-angular-frontend:${{ github.sha }}
            ghcr.io/alfremu/devops-challenge-flask-angular-frontend:latest
